version: '3.1'

services:
  postgres-ens:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ensdata
      - POSTGRES_DB=ensdata
    ports:
      - "5432:5432"
    volumes:
      - ensdata-postgresql:/var/lib/postgresql/data

volumes:
  ensdata-postgresql: